// generated by tools/panicimplgen.go; do not edit
package iface

func (c currentChannel) Do(what []byte) {
	panic("attempt to call Do() method of iface.CurrentChannel")
}

func (c currentChannel) IsQuery() bool {
	panic("attempt to call IsQuery() method of iface.CurrentChannel")
}

func (c currentChannel) Leave(reason []byte) {
	panic("attempt to call Leave() method of iface.CurrentChannel")
}

func (c currentChannel) Name() string {
	panic("attempt to call Name() method of iface.CurrentChannel")
}

func (c currentChannel) Say(what []byte) {
	panic("attempt to call Say() method of iface.CurrentChannel")
}

func (c currentChannel) Server() Server {
	panic("attempt to call Server() method of iface.CurrentChannel")
}
